# Generated by Django 3.0.3 on 2020-05-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.CharField(choices=[('ST', 'Study'), ('SP', 'Sports'), ('VO', 'Volunteer'), ('PO', 'Project'), ('EN', 'Entertainment'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('address', models.TextField()),
                ('male_wanted', models.IntegerField(default=0)),
                ('female_wanted', models.IntegerField(default=0)),
                ('male_joined', models.IntegerField(default=0)),
                ('female_joined', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('watched_times', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='favored_users',
            field=models.ManyToManyField(related_name='favoured_activity', through='activities.Favourite', to='users.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='joined_users',
            field=models.ManyToManyField(related_name='joined_activity', through='activities.Join', to='users.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_activity', through='activities.Like', to='users.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
