# Generated by Django 3.0.3 on 2020-05-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('activity_id', models.IntegerField(default=0)),
                ('content', models.CharField(default='leave something', max_length=100)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=15)),
                ('like_num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Comment_reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_id', models.IntegerField(default=0)),
                ('from_id', models.IntegerField(default=0)),
                ('from_name', models.CharField(default='someone', max_length=15)),
                ('to_id', models.IntegerField(default=0)),
                ('to_name', models.CharField(default='someone', max_length=15)),
                ('content', models.CharField(default='leave something', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'comment_reply',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='someone', max_length=15)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Comment_reply_like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('comment_reply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment_reply')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.User')),
            ],
            options={
                'db_table': 'comment_reply_like',
            },
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='like_user',
            field=models.ManyToManyField(related_name='comment_replys', through='comment.Comment_reply_like', to='comment.User'),
        ),
        migrations.CreateModel(
            name='Comment_like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.User')),
            ],
            options={
                'db_table': 'comment_like',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='like_user',
            field=models.ManyToManyField(related_name='comments', through='comment.Comment_like', to='comment.User'),
        ),
    ]
