# Generated by Django 3.0.3 on 2020-05-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_like',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment_like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment_reply_like',
            old_name='comment_reply_id',
            new_name='comment_reply',
        ),
        migrations.RenameField(
            model_name='comment_reply_like',
            old_name='user_id',
            new_name='user',
        ),
    ]
