# Generated by Django 3.0.3 on 2020-05-19 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200519_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_reply',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='comment',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='comment.Comment'),
        ),
    ]
