# Generated by Django 3.0.3 on 2020-05-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('comment', '0003_auto_20200519_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_user',
            field=models.ManyToManyField(related_name='comments', through='comment.Comment_like', to='users.User'),
        ),
        migrations.AlterField(
            model_name='comment_like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='like_user',
            field=models.ManyToManyField(related_name='comment_replys', through='comment.Comment_reply_like', to='users.User'),
        ),
        migrations.AlterField(
            model_name='comment_reply_like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
